### ISSUE TITLE
Contract Addresses are wrong

### ISSUE THREAD

**Issue by samlaf** [cairoeth/preconfirmations#1]
`make run-operator` results in
```
panic: Failed to create EL Reader, Writer and Subscriber: Failed to create AVSRegistryContractBindings: Failed to fetch ServiceManager address: no contract code at given address
```

Seems like you redeployed and forgot to update the contracts? Both the [deployment_output](https://github.com/cairoeth/preconfirmations/blob/8c5e3592c6d1df50038159376299b78d2fbf2332/contracts/script/output/31337/preconf_avs_deployment_output.json#L7) and operator [config](https://github.com/cairoeth/preconfirmations/blob/8c5e3592c6d1df50038159376299b78d2fbf2332/preconf-operator/config.yaml#L10) list 0x9E545E3C0baAB3E08CdfD552C960A1050f373042 as the avs registry coordinator, but

```
make run-anvil
cast code 0x9E545E3C0baAB3E08CdfD552C960A1050f373042
```
results in `0x`

**Comment by cairoeth** [comment]
Not able to replicate to get that error. Can you run:
```
make run-anvil
cast code 0x9E545E3C0baAB3E08CdfD552C960A1050f373042 --rpc-url http://127.0.0.1:8545
```

It should return the bytecode

**Comment by cairoeth** [comment]
[Anvil state](https://github.com/cairoeth/preconfirmations/blob/8c5e3592c6d1df50038159376299b78d2fbf2332/contracts/anvil-state.json) contains the bytecode for address `0x9e545e3c0baab3e08cdfd552c960a1050f373042`, so if anvil loads it correctly, it should be good

**Comment by samlaf** [comment]
My bad! I had a docker instance of anvil running with 0.0.0.0:8545 redirecting to it, so it was getting precedence by the cast default --rpc-url. I always assumed the cast default rpc-url was localhost:8545 but it seems like its not... or there's some funky networking redirect in docker that I don't understand. Closing :)
