### ISSUE TITLE
no make run-rpc command

### ISSUE THREAD

**Issue by samlaf** [cairoeth/preconfirmations#2]
The README says to run `make run-rpc` in https://github.com/cairoeth/preconfirmations?tab=readme-ov-file#rpc, but there is no such command in the makefile.

Guessing you ran into trouble making the run-rpc work and decided to leave it out, given that the rpc server is not started by `make run-all` either.

Should we just remove that section from readme (and rpc dir from repo maybe?)

**Comment by cairoeth** [comment]
forgot to add it in makefile! added in #4.
